digits = 'ABCDEFGHIJKLMNOPQRSTUVWXY'

grids = ['NSD...YEJ.PK.A....BGW.MH.M...HSX..NOJT.EU..A.V.L..KP.U...B.L.HRWC..NX..Y.EOLQ..GRWCH..IS..T...EUA.F.O.EY..A....L.BG.MRCHXD.I.P..AKV..LQRMWCH.NSDI..O..TY.E..FKPU..BGLC..HMDIS.XQ..BL.CH...N.DIYO..JA.PKURW..MXDI.S.OYEJ.PU.KB...V...D..EJOTUPAFKB.VG....MWXD.ISEJOT..U..P..BLQH.W..U.K.PBG.Q.W.CHM..XI.E.T.YV...QCHMR.XSD...TY..F.U.AW.MHRD..SX.TE.O.U.KPG.VQ..EO.TF..U.B...Q....R.NXSDE.....PU.F...Q.M...W..D...F.......BCWHM.IXDNS.O.T.DISN.J.T..F..PUL.......W.BGQLV..RWC.XIN...E..K.AUF..R...N..D.YJ.....P.LQ...FK.P.LQVB.HCMRW....XO...JIN...OT.E.K..UAQG...RW..MGLVQ.M...H.D....EJTY....KJ.YTEPU..K.GQ.BR.M.....D.HM..CN.X.IJEO....K.A.VGBL',
         ] 
